### ISSUE TITLE
Problem w/ Jupyter notebooks

### ISSUE THREAD

**Issue by santiagobadia** [gridap/Tutorials#11]
Hi @fverdugo 

It seems that when you clone tutorials, and proceed as indicated in the documentation, calling the first time `using Gridap` from the jupyter notebook returns an exception. If you run `using Julia` from the REPL then the jupyter notebook works. Some users have told me this, and I have been able to reproduce the same issue. Can you reproduce it too? If yes, we can probably ask to do using Gridap before launching the notebooks in the documentation.

**Comment by fverdugo** [comment]
@santiagobadia I am able to run the first notebook correctly. What is the exception you get?

Make sure that everybody follows all the steps in the docs https://gridap.github.io/Tutorials/stable/#How-to-run-the-notebooks-locally-1:

```
$ cd Tutorials
$ git pull
$ julia --project=.
pkg> instantiate
julia> include("deps/build.jl")
julia> using IJulia
julia> notebook(dir=pwd())
```

In particular, this ensures that you run the right version of the notebooks in an environment with the right version of Gridap.
