### ISSUE TITLE
TransientHeatEq benchmark

### ISSUE THREAD

**Issue by OVGULIU** [gridap/Tutorials#15]
also a bug:

ERROR: LoadError: UndefVarError: FaceLabels not defined
Stacktrace:

**Comment by fverdugo** [comment]
Please, provide a reproducer otherwise it is impossible to help.

I seems that you are not using the right version of Gridap for the code you want to execute. Which Gridap version are you using?

**Comment by OVGULIU** [comment]
Gridap v0.8.0

**Comment by OVGULIU** [comment]
in Version + Gridap v0.7.1 we can find the same error:
LoadError: **UndefVarError: FaceLabels not defined**

**Comment by fverdugo** [comment]
It seems that you are executing code for a much older version perhaps 0.5 or 0.6...

Use the latest version of the tutorials available in the Tutorials repo branch master. It should work with Gridap 0.7 at this moment.

**Comment by fverdugo** [comment]
By the way, the transient heat equation tutorial is under construction. Don't expect it to work...
