### ISSUE TITLE
Explain attribution of tags for simple boundary

### ISSUE THREAD

**Issue by rveltz** [gridap/Tutorials#21]
Hi,

In the tutorial on Darcy Equation, you write

> Note that the Dirichlet boundary for the flux are the bottom and top sides of the squared domain (identified with the boundary tags 5, and 6 respectively), 

Given a `model`, how can you tell which faces are which? How can we access the coordinates?

Thank you for your help,

Bests

**Comment by fverdugo** [comment]
Perhaps the easiest way of seeing the data in a model is by writing it into vtu format and visualizing it in paraview

```julia
writevtk(model,"model")
```

Take a look to this section, where the output of this command is explained:
https://gridap.github.io/Tutorials/stable/pages/t001_poisson/#Discrete-model-1

For the nodal coordinates in a model:
```julia
using Gridap.Geometry: get_grid, get_nodal_coordinates
grid = get_grid(model)
node_to_x = get_nodal_coordinates(grid)
```

**Comment by santiagobadia** [comment]
There is logic behind this numbering. For Cartesian models, we use a sort based on lexicographical order, i.e., (0,0), (1,0), (0,1), (1,1) in 2D for vertices.

- For vertices it is straightforward.
- For edges, we start with the ones in the direction 1(X), next 2(Y), next 3(Z). For every edge in these sets, lexicographical order based on the vertex in which the edge starts.
- For faces, we consider the faces in (X,Y), next (X,Z), next (Y,Z), and for each, lexicographical order on the origin of the face.

Some simple examples:

# SEGMENT

1 *  --- 3 --- * 2

# QUAD

3 *  --- 6 --- * 4
|                     |
7                   8
|                     |
1 *  --- 5 --- * 2

In any case, as @fverdugo says you can always visualize the polytope (geometry) you are using. You can do it for the HEX. It would take a while to draw it here.

**Comment by rveltz** [comment]
Thank you for your help. I do this you should write a simple plot recipe instead of relying on vtk even if it only handles simple geometries.
