### ISSUE TITLE
Move CI from Travis to GH actions

### ISSUE THREAD

**Issue by fverdugo** [gridap/Tutorials#56]
Step number 0 would be to move the CI from Travis to GH actions and push a tag for the current version (0.14) which is not yet done

**Comment by amartinhuertas** [comment]
Step number 0 would be to move the CI from Travis to GH actions and push a tag for the current version (0.14) which is not yet done

**Comment by amartinhuertas** [comment]
Hi @fverdugo ! @oriolcg ! Do u know why it is required to have an isolated module at the end of the runtests.jl script? https://github.com/gridap/Tutorials/blob/master/test/runtests.jl#L23 Isn't this being already executed in the for loop?

**Comment by fverdugo** [comment]
It seems that the FSI tutorial is being run 2 times. 

I think the implementation of this file can be improved (specifically the loop over the different tutorials). The generation of the temporary module with random name leads to issues in some cases (I have ended more than one time on the error `error("File $tmpfile already exists!")`).
Instead I would use the name of the tutorial to name the temporary module and the file that contains, which can be stored in a folder safely created with `mktempdir`.

**Comment by amartinhuertas** [comment]
> It seems that the FSI tutorial is being run 2 times.

Ok, I have commented out the declaration of the isolated module.

> (I have ended more than one time on the error error("File $tmpfile already exists!")).

Yes, that's something I have also observed in my machine. 

> Instead I would use the name of the tutorial to name the temporary module and the file that contains, which can be stored in a folder safely created with mktempdir.

Good call. Done in ca0ecccdd02e67c30cb5bc63f975b2cf2b75735b!
